server:
  port: 8080
spring:
  application:
    name: "JavaAvanzado"
  devtools:
    add-properties: false
  profiles:
    include: null
  datasource:
    url: "jdbc:mysql://localhost:3306/test"
    username: "root"
    password: "123456"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.MySQL8Dialect"